<!-- 
@component 
A component for animating the appearance of text by characters or words.
-->
<script lang="ts">
	import { cn } from '$lib/utils/shadcn';
	import { animate, stagger } from 'motion';

	interface Props {
		/**
		 * Unique id used for animation.
		 * Autogenerated if not provided.
		 * @default undefined
		 */
		id?: string;
		/**
		 * Text to be animated.
		 */
		text: string;
		/**
		 * Additional CSS classes for layout or styling.
		 * @default ''
		 */
		className?: string;
		/**
		 * Character or word separator.
		 * Use `''` to animate each character separately,
		 * or `' '` to animate words.
		 * @default ''
		 */
		separator?: '' | ' ';
		/**
		 * Delay between each animation step.
		 * @default 0.15
		 */
		delay?: number;
		/**
		 * Duration of animation.
		 * @default 0.5
		 */
		duration?: number;
		/**
		 * Direction in which text will move.
		 * @default 'UP'
		 */
		direction?: keyof typeof animationDirection;
	}
	let {
		id = `staggered-text-${Math.random().toString(36).slice(2, 12)}`,
		text,
		className = '',
		separator = '',
		delay = 0.15,
		duration = 0.5,
		direction = 'UP'
	}: Props = $props();

	const animationDirection = {
		RIGHT: { opacity: 1, x: [-20, 0], y: [0, 0] },
		UP: { opacity: 1, y: [15, 0] },
		DOWN: { opacity: 1, y: [-15, 0] }
	};

	// svelte-ignore state_referenced_locally
	let textSplit = text.split(separator);

	$effect(() => {
		animate(`#${id} span`, animationDirection[direction], {
			delay: stagger(delay),
			duration: duration
		});
	});
</script>

<div
	{id}
	class={cn('flex', className)}
>
	<!-- eslint-disable-next-line svelte/require-each-key -->
	{#each textSplit as char, index}
		<span class="flex opacity-0">
			{char}
		</span>

		<!-- add spaces between words if split is by spaces -->
		{#if separator && index < textSplit.length - 1}
			<span class="opacity-0">&nbsp;</span>
		{/if}
	{/each}
</div>
